// Copyright (C) 2019-2020 Zilliz. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance
// with the License. You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License
// is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
// or implied. See the License for the specific language governing permissions and limitations under the License

#pragma once

#include <tuple>
#include <map>
#include <limits>
#include <cmath>
#include <google/protobuf/text_format.h>
#include <knowhere/common/MetricType.h>
#include <knowhere/index/vector_index/helpers/IndexParameter.h>
#include <knowhere/index/vector_index/adapter/VectorAdapter.h>
#include <knowhere/index/vector_index/VecIndexFactory.h>

#include "pb/index_cgo_msg.pb.h"

#include "indexbuilder/VecIndexCreator.h"
#include "indexbuilder/index_c.h"
#include "DataGen.h"
#include "indexbuilder/utils.h"
#include "indexbuilder/helper.h"
#include "indexbuilder/ScalarIndexCreator.h"

//namespace indexcgo = milvus::proto::indexcgo;

namespace milvus::test {

using milvus::proto::indexcgo::TypeParams;
using milvus::proto::indexcgo::IndexParams;

#ifdef MILVUS_GPU_VERSION
extern int DEVICEID;
#endif

using milvus::indexbuilder::MapParams;
using milvus::indexbuilder::ScalarIndexCreator;
using knowhere::scalar::OperatorType;
using ScalarTestParams = std::pair<MapParams, MapParams>;
using QueryResultPtr = std::unique_ptr<milvus::indexbuilder::VecIndexCreator::QueryResult>;

knowhere::Config
generate_conf(const knowhere::IndexType& index_type, const knowhere::MetricType& metric_type);

std::tuple<TypeParams, IndexParams>
generate_params(const knowhere::IndexType& index_type, const knowhere::MetricType& metric_type);

GeneratedData
GenDataset(int64_t N, const knowhere::MetricType& metric_type, bool is_binary, int64_t dim = DIM);

void
PrintQueryResult(const QueryResultPtr& result);

float
L2(const float* point_a, const float* point_b, int dim);

int
hamming_weight(uint8_t n);

float
Jaccard(const uint8_t* point_a, const uint8_t* point_b, int dim);

float
CountDistance(const void* point_a,
              const void* point_b,
              int dim,
              const knowhere::MetricType& metric,
              bool is_binary = false);

void
CheckDistances(const QueryResultPtr& result,
               const knowhere::DatasetPtr& base_dataset,
               const knowhere::DatasetPtr& query_dataset,
               const knowhere::MetricType& metric,
               const float threshold = 1.0e-5);

std::string
generate_type_params(const MapParams& m);

std::string
generate_index_params(const MapParams& m);

// TODO: std::is_arithmetic_v, hard to compare float point value. std::is_integral_v.
template <typename T, typename = typename std::enable_if_t<std::is_arithmetic_v<T> || std::is_same_v<T, std::string>>>
inline
std::vector<T>
GenArr(int64_t n) {
    auto max_i8 = std::numeric_limits<int8_t>::max() - 1;
    std::vector<T> arr;
    arr.resize(n);
    for (int64_t i = 0; i < n; i++) {
        arr[i] = static_cast<T>(rand() % max_i8);
    }
    std::sort(arr.begin(), arr.end());
    return arr;
};

std::vector<std::string>
GenStrArr(int64_t n);

template <>
inline 
std::vector<std::string>
GenArr<std::string>(int64_t n) {
    return GenStrArr(n);
};

template <typename T, typename = typename std::enable_if_t<std::is_arithmetic_v<T>>>
inline 
std::vector<ScalarTestParams>
GenParams() {
    std::vector<ScalarTestParams> ret;
    ret.emplace_back(ScalarTestParams(MapParams(), {{"index_type", "inverted_index"}}));
    ret.emplace_back(ScalarTestParams(MapParams(), {{"index_type", "flat"}}));
    return ret;
};

std::vector<ScalarTestParams>
GenBoolParams();

std::vector<ScalarTestParams>
GenStringParams();

void
PrintMapParam(const ScalarTestParams& tp);

void
PrintMapParams(const std::vector<ScalarTestParams>& tps);

template <typename T>
inline 
void
build_index(const std::unique_ptr<ScalarIndexCreator<T>>& creator, const std::vector<T>& arr) {
    const int64_t dim = 8;  // not important here
    auto dataset = knowhere::GenDataset(arr.size(), dim, arr.data());
    creator->Build(dataset);
};

// memory generated by this function should be freed by the caller.
knowhere::DatasetPtr
GenDsFromPB(const google::protobuf::Message& msg);

}  // namespace milvus::test
